### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by gruebel** [jpetrucciani/bandit-check#11]
hey @jpetrucciani thanks for creating this GHA 🚀 Is it possible to create a new tag + release? Since I'm using the latest commit hash of the master branch, Dependabot recommends me to downgrade to the `1.7.0` version 😄

**Comment by jpetrucciani** [comment]
Good call! apologies for that - let me see if i can get some tags and releases created!

**Comment by jpetrucciani** [comment]
Just made new tags+releases for `1.7.1`, `1.7.2`, `1.7.3`, `1.7.4`!

**Comment by gruebel** [comment]
Awesome thanks!
